server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false # ?? ????? client? ??? ???? (default: true)
    fetch-registry: false       # true? ??, ??? ??? Eureka Server? ???? ?? ?????? ??? ?? (default: true)